spring:
  profiles:
    active: demo1
---
spring:
  application:
    name: demo_hospital_project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    url: jdbc:mysql://111.229.139.12:3306/demo_hospital_project?serverTimezone=GMT%2B8
    username: root
    password: root
  profiles: demo1

server:
  port: 12301

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hospital.xhu.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 显示MyBatis的log信息到控制台

cache:
  cache_size: 1000
  limit_time: 1200  # LRU删除的时间
---
spring:
  application:
    name: demo_hospital_project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    url: jdbc:mysql://111.229.139.12:3306/demo_hospital_project?serverTimezone=GMT%2B8
    username: root
    password: root
  profiles: demo2

server:
  port: 12302

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hospital.xhu.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 显示MyBatis的log信息到控制台

cache:
  cache_size: 1000
  limit_time: 1200  # LRU删除的时间

