spring:
  application:
    name: demo_hospital_project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    url: jdbc:mysql://111.229.139.12:3306/demo_hospital_project?serverTimezone=GMT%2B8
    username: root
    password: root

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hospital.xhu.demo.entity
